import pluginVue from 'eslint-plugin-vue';
import vueParser from 'vue-eslint-parser';

export default [
	{
		ignores: ['node_modules/**', 'dist/**'],
	},
	{
		files: ['**/*.vue', '**/*.js', '**/*.jsx', '**/*.cjs', '**/*.mjs'],
		languageOptions: {
			ecmaVersion: 'latest',
			sourceType: 'module',
			parser: vueParser,
			parserOptions: {
				ecmaVersion: 'latest',
			},
			globals: {
				process: 'readonly',
				APP_CONFIG: 'readonly',
				window: 'readonly',
				document: 'readonly',
				console: 'readonly',
				setTimeout: 'readonly',
				clearTimeout: 'readonly',
				setInterval: 'readonly',
				clearInterval: 'readonly',
				localStorage: 'readonly',
				sessionStorage: 'readonly',
				navigator: 'readonly',
				fetch: 'readonly',
				URL: 'readonly',
				Blob: 'readonly',
				File: 'readonly',
				FileReader: 'readonly',
				FormData: 'readonly',
				Audio: 'readonly',
				Image: 'readonly',
				IntersectionObserver: 'readonly',
				MutationObserver: 'readonly',
				ResizeObserver: 'readonly',
				requestAnimationFrame: 'readonly',
				cancelAnimationFrame: 'readonly',
				performance: 'readonly',
				WebSocket: 'readonly',
				XMLHttpRequest: 'readonly',
				AbortController: 'readonly',
				AbortSignal: 'readonly',
				Headers: 'readonly',
				Request: 'readonly',
				Response: 'readonly',
				JSON: 'readonly',
				Promise: 'readonly',
				Symbol: 'readonly',
				WeakMap: 'readonly',
				WeakSet: 'readonly',
				Proxy: 'readonly',
				Reflect: 'readonly',
				Map: 'readonly',
				Set: 'readonly',
				Date: 'readonly',
				Math: 'readonly',
				RegExp: 'readonly',
				Error: 'readonly',
				TypeError: 'readonly',
				RangeError: 'readonly',
				SyntaxError: 'readonly',
				ReferenceError: 'readonly',
				parseInt: 'readonly',
				parseFloat: 'readonly',
				isNaN: 'readonly',
				isFinite: 'readonly',
				decodeURI: 'readonly',
				decodeURIComponent: 'readonly',
				encodeURI: 'readonly',
				encodeURIComponent: 'readonly',
				undefined: 'readonly',
				NaN: 'readonly',
				Infinity: 'readonly',
				Object: 'readonly',
				Function: 'readonly',
				Boolean: 'readonly',
				String: 'readonly',
				Number: 'readonly',
				Array: 'readonly',
			},
		},
		plugins: {
			vue: pluginVue,
		},
		rules: {
			'no-unused-vars': 'warn',
			'no-undef': 'error',
			indent: 'off',
			'no-tabs': 'off',
			'no-mixed-spaces-and-tabs': 'off',
			'vue/no-unused-components': 'off',
			'vue/multi-word-component-names': 'off',
			'vue/no-template-key': 'off',
			'vue/require-v-for-key': 'error',
			'vue/no-use-v-if-with-v-for': 'error',
		},
	},
];
